function rspdat = getrespdata(fileToRead1)
%IMPORTFILE(FILETOREAD1)
%  Imports data from the specified file
%  FILETOREAD1:  file to read

%  Auto-generated by MATLAB on 06-Nov-2007 17:49:02

DELIMITER = '\t';
HEADERLINES = 8;

% Import the file
rspdat = importdata([fileToRead1 '.txt'], DELIMITER, HEADERLINES);

% % Create new variables in the base workspace from those fields.
% vars = fieldnames(newData1);
% for i = 1:length(vars)
%     assignin('base', vars{i}, newData1.(vars{i}));
% end

